- name: Install epel repo
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: started
    enabled: true

- name: Copy nginx configuration file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: reloaded

- name: Copy audit rules file
  ansible.builtin.copy:
    src: roles/web/files/audit.rules
    dest: /etc/audit/rules.d/audit.rules

- name: Install audispd-plugins
  ansible.builtin.yum:
    name: audispd-plugins
    state: present
    
- name: Copy auditd configuration file
  ansible.builtin.copy:
    src: auditd.conf
    dest: /etc/audit/auditd.conf

- name: Copy au-remote configuration file
  ansible.builtin.copy:
    src: au-remote.conf
    dest: /etc/audisp/plugins.d/au-remote.conf
    
- name: Copy audisp-remote configuration file
  ansible.builtin.copy:
    src: audisp-remote.conf
    dest: /etc/audisp/audisp-remote.conf

- name: Restart auditd
  ansible.builtin.command: /sbin/service auditd restart
